import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('customer', 'Customer'), ('supplier', 'Supplier')], default='customer', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okpd2', models.CharField(choices=[('29.10', '29.10'), ('29.20', '29.20'), ('29.31', '29.31'), ('29.32', '29.32')], max_length=5, verbose_name='Сфера деятельности по ОКПД2')),
                ('description', models.TextField(verbose_name='Описание заказа')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма контракта')),
                ('delivery_region', models.CharField(choices=[
        ("Алтайский край", "Алтайский край"),
        ("Амурская область", "Амурская область"),
        ("Архангельская область", "Архангельская область"),
        ("Астраханская область", "Астраханская область"),
        ("Байконур", "Байконур"),
        ("Белгородская область", "Белгородская область"),
        ("Брянская область", "Брянская область"),
        ("Владимирская область", "Владимирская область"),
        ("Волгоградская область", "Волгоградская область"),
        ("Вологодская область", "Вологодская область"),
        ("Воронежская область", "Воронежская область"),
        ("Донецкая Народная Республика", "Донецкая Народная Республика"),
        ("Еврейская автономная область", "Еврейская автономная область"),
        ("Забайкальский край", "Забайкальский край"),
        ("Запорожская область", "Запорожская область"),
        ("Ивановская область", "Ивановская область"),
        ("Иркутская область", "Иркутская область"),
        ("Кабардино-Балкарская Республика", "Кабардино-Балкарская Республика"),
        ("Калининградская область", "Калининградская область"),
        ("Калужская область", "Калужская область"),
        ("Камчатский край", "Камчатский край"),
        ("Карачаево-Черкесская Республика", "Карачаево-Черкесская Республика"),
        ("Кемеровская область - Кузбасс", "Кемеровская область - Кузбасс"),
        ("Кировская область", "Кировская область"),
        ("Костромская область", "Костромская область"),
        ("Краснодарский край", "Краснодарский край"),
        ("Красноярский край", "Красноярский край"),
        ("Курганская область", "Курганская область"),
        ("Курская область", "Курская область"),
        ("Ленинградская область", "Ленинградская область"),
        ("Липецкая область", "Липецкая область"),
        ("Луганская Народная Республика", "Луганская Народная Республика"),
        ("Магаданская область", "Магаданская область"),
        ("Москва", "Москва"),
        ("Московская область", "Московская область"),
        ("Мурманская область", "Мурманская область"),
        ("Ненецкий автономный округ (Архангельская область)", "Ненецкий автономный округ (Архангельская область)"),
        ("Нижегородская область", "Нижегородская область"),
        ("Новгородская область", "Новгородская область"),
        ("Новосибирская область", "Новосибирская область"),
        ("Омская область", "Омская область"),
        ("Оренбургская область", "Оренбургская область"),
        ("Орловская область", "Орловская область"),
        ("Пензенская область", "Пензенская область"),
        ("Пермский край", "Пермский край"),
        ("Приморский край", "Приморский край"),
        ("Псковская область", "Псковская область"),
        ("Республика Адыгея (Адыгея)", "Республика Адыгея (Адыгея)"),
        ("Республика Алтай", "Республика Алтай"),
        ("Республика Башкортостан", "Республика Башкортостан"),
        ("Республика Бурятия", "Республика Бурятия"),
        ("Республика Дагестан", "Республика Дагестан"),
        ("Республика Ингушетия", "Республика Ингушетия"),
        ("Республика Калмыкия", "Республика Калмыкия"),
        ("Республика Карелия", "Республика Карелия"),
        ("Республика Коми", "Республика Коми"),
        ("Республика Крым", "Республика Крым"),
        ("Республика Марий Эл", "Республика Марий Эл"),
        ("Республика Мордовия", "Республика Мордовия"),
        ("Республика Саха (Якутия)", "Республика Саха (Якутия)"),
        ("Республика Северная Осетия-Алания", "Республика Северная Осетия-Алания"),
        ("Республика Татарстан (Татарстан)", "Республика Татарстан (Татарстан)"),
        ("Республика Тыва", "Республика Тыва"),
        ("Республика Хакасия", "Республика Хакасия"),
        ("Ростовская область", "Ростовская область"),
        ("Рязанская область", "Рязанская область"),
        ("Самарская область", "Самарская область"),
        ("Санкт-Петербург", "Санкт-Петербург"),
        ("Саратовская область", "Саратовская область"),
        ("Сахалинская область", "Сахалинская область"),
        ("Свердловская область", "Свердловская область"),
        ("Севастополь", "Севастополь"),
        ("Смоленская область", "Смоленская область"),
        ("Ставропольский край", "Ставропольский край"),
        ("Тамбовская область", "Тамбовская область"),
        ("Тверская область", "Тверская область"),
        ("Томская область", "Томская область"),
        ("Тульская область", "Тульская область"),
        ("Тюменская область", "Тюменская область"),
        ("Удмуртская Республика", "Удмуртская Республика"),
        ("Ульяновская область", "Ульяновская область"),
        ("Хабаровский край", "Хабаровский край"),
        ("Ханты-Мансийский автономный округ - Югра (Тюменская область)", "Ханты-Мансийский автономный округ - Югра (Тюменская область)"),
        ("Херсонская область", "Херсонская область"),
        ("Челябинская область", "Челябинская область"),
        ("Чеченская Республика", "Чеченская Республика"),
        ("Чувашская Республика - Чувашия", "Чувашская Республика - Чувашия"),
        ("Чукотский автономный округ", "Чукотский автономный округ"),
        ("Ямало-Ненецкий автономный округ (Тюменская область)", "Ямало-Ненецкий автономный округ (Тюменская область)"),
        ("Ярославская область", "Ярославская область"),
    ], max_length=255, verbose_name='Регион поставки')),
                ('law_type', models.CharField(choices=[('44_FZ', '44-ФЗ'), ('223_FZ', '223-ФЗ')], default='44_FZ', max_length=6, verbose_name='Закон, по которому организуется заказ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время запроса')),
                ('request_data', models.JSONField(verbose_name='Параметры запроса')),
                ('recommended_suppliers', models.JSONField(verbose_name='Рекомендованные поставщики')),
                ('top_only', models.BooleanField(default=False, verbose_name='Только топ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(verbose_name='Полное наименование')),
                ('short_name', models.TextField(blank=True, null=True, verbose_name='Краткое наименование')),
                ('short_name_english', models.TextField(blank=True, null=True, verbose_name='Краткое наименование (английский)')),
                ('judicial_address', models.TextField(blank=True, null=True, verbose_name='Юридический адрес')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('leader', models.TextField(blank=True, null=True, verbose_name='Руководитель')),
                ('registration_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('okved', models.CharField(blank=True, max_length=10, null=True, verbose_name='ОКВЭД')),
                ('index_due_diligence', models.IntegerField(blank=True, null=True, verbose_name='Индекс должной осмотрительности')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('ogrn', models.CharField(max_length=15, unique=True, verbose_name='ОГРН')),
                ('okpo', models.CharField(max_length=12, unique=True, verbose_name='ОКПО')),
                ('okfs', models.CharField(choices=[('Частная собственность', 'Частная собственность'), ('Государственная собственность', 'Государственная собственность'), ('Индивидуальные предприниматели', 'Индивидуальные предприниматели'), ('Собственность иностранных граждан и лиц без гражданства', 'Собственность иностранных граждан и лиц без гражданства'), ('Иная смешанная российская собственность', 'Иная смешанная российская собственность'), ('Совместная частная и иностранная собственность', 'Совместная частная и иностранная собственность'), ('Федеральная собственность', 'Федеральная собственность')], max_length=64, verbose_name='ОКФС')),
                ('okopf', models.CharField(choices=[('Общества с ограниченной ответственностью', 'Общества с ограниченной ответственностью'), ('Акционерные общества', 'Акционерные общества'), ('Индивидуальные предприниматели', 'Индивидуальные предприниматели'), ('Закрытые акционерные общества', 'Закрытые акционерные общества'), ('Открытые акционерные общества', 'Открытые акционерные общества'), ('Казенные учреждения', 'Казенные учреждения')], max_length=64, verbose_name='ОКОПФ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okpd2', models.CharField(choices=[('29.10', '29.10'), ('29.20', '29.20'), ('29.31', '29.31'), ('29.32', '29.32')], max_length=5, verbose_name='Код ОКПД2')),
                ('supplier', models.ForeignKey(limit_choices_to={'role': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Поставщик')),
            ],
            options={
                'unique_together': {('supplier', 'okpd2')},
            },
        ),
    ]
