# Generated by Django 5.1.5 on 2025-01-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='okpd2',
            field=models.CharField(choices=[('29.10', '29.10'), ('29.20', '29.20'), ('29.31', '29.31'), ('29.32', '29.32')], max_length=5, verbose_name='Сфера деятельности по ОКПД2'),
        ),
    ]
