# Generated by Django 5.1.5 on 2025-03-26 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250316_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okpd2', models.CharField(max_length=10, verbose_name='Код ОКПД2')),
                ('supplier', models.ForeignKey(limit_choices_to={'role': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Поставщик')),
            ],
            options={
                'unique_together': {('supplier', 'okpd2')},
            },
        ),
    ]
